#title: PUCSD ALUMS
#description: 
#google_analytics: 
#show_downloads: true
#theme: jekyll-theme-minimal

#gems:
#  - jekyll-mentions

lsi: false
safe: true
source: [https://kiranmak.github.io]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
